replicaCount: 1

image:
  repository: arthurjguerra18/revwallet
  pullPolicy: IfNotPresent
  tag: v0.7.12

imagePullSecrets: []
nameOverride: "revwallet-api"
fullnameOverride: "revwallet-api"

credentials:
  secret: revwallet-db
  dbUsernameSecretKey: dbuser
  dbPasswordSecretKey: dbpassword
  dbNameSecretKey: dbname
  dbHostSecretKey: dbhost

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "revwallet-api-sa"

podAnnotations: {}
podLabels:
  app: revwallet-api

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 5000

ingress:
  enabled: false

resources:
  limits:
    cpu: 100m
  requests:
    cpu: 100m

livenessProbe:
  httpGet:
    path: /wallet/
    port: http
readinessProbe:
  httpGet:
    path: /wallet/
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

persistentVolumeClaim:
  name: revwallet-api-log-volume-claim
  accessModes: ReadWriteOnce
  size: 1Gi
  storageClass: ""  # set to default

volumes: 
  - name: revwallet-api-log-volume
    persistentVolumeClaim:
      claimName: revwallet-api-log-volume-claim

volumeMounts:
  - name: revwallet-api-log-volume
    mountPath: /var/log/revwallet

nodeSelector: {}

tolerations: []

affinity: {}
