services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    networks:
      - revwallet_network

  revwallet_db:
    image: postgres:latest
    container_name: revwallet_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: revwallet
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - revwallet_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d revwallet -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  revwallet_api:
    image: arthurjguerra18/revwallet:${GITHUB_SHA:-test}
    container_name: revwallet_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      revwallet_db:
        condition: service_healthy
      prometheus:
        condition: service_started
    environment:
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
      DB_NAME: revwallet
      DB_HOST: revwallet_db
    ports:
      - "5000:5000"
    networks:
      - revwallet_network
    links:
      - revwallet_db

networks:
  revwallet_network:
    driver: bridge

volumes:
  db_data: