services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: revwallet
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - revwallet_network

  revwallet:
    image: revwallet:latest
    container_name: revwallet_app
    depends_on:
      - db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: revwallet
    ports:
      - "5000:5000"
    networks:
      - revwallet_network
    links:
      - db

networks:
  revwallet_network:
    driver: bridge

volumes:
  db_data: