image:
  repository: arthurjguerra18/revwallet
  pullPolicy: IfNotPresent
  tag: v0.7.12
  
env:
  DB_USERNAME: revwallet
  DB_PASSWORD: mypassword
  DB_NAME: revwallet
  DB_HOST: revwallet-db.revwallet-dev.svc.cluster.local