service:
  type: NodePort
  port: 8080

replicaCount: 1

ingress:
  enabled: false

extraVolumes:
  - name: nginx-html
    configMap:
      name: nginx-html
  - name: nginx-conf
    configMap:
      name: nginx-conf

extraVolumeMounts:
  - name: nginx-html
    mountPath: /opt/bitnami/nginx/html/
  - name: nginx-conf
    mountPath: /opt/bitnami/nginx/conf/nginx.conf
    subPath: nginx.conf

commonLabels:
  app: nginx
