apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    editable: true
    is_default: true
    access: proxy
    url: http://prometheus:9090/prometheus
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
