global:
  scrape_interval: 15s
  evaluation_interval:  15s

scrape_configs:
  - job_name: 'revwallet-api'
    static_configs:
      - targets: ['revwallet-api:5000']

remote_write:
- url: http://localhost:9090/prometheus/api/prom/push