apiVersion: v1
kind: Secret
metadata:
  name: revwallet-db
type: Opaque
stringData:
  dbuser: revwallet
  dbpassword: mypassword
  dbname: revwallet
  dbhost: revwallet-db
  postgres-password: mypassword
  password: mypassword
  replication-password: mypassword