apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: revwallet-volume-claim
  labels:
    app: revwallet-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi