#!/bin/bash

if [[ "$1" == "--delete" ]]; then
  helm -n revwallet-dev uninstall nginx
  helm -n revwallet-dev uninstall alloy
  helm -n revwallet-dev uninstall loki
  helm -n revwallet-dev uninstall grafana
  helm -n revwallet-dev uninstall prometheus
  helm -n revwallet-dev uninstall revwallet-api
  helm repo remove grafana prometheus-community bitnami
  kubectl -n revwallet-dev delete -f k8s/revwallet-db
  kubectl -n revwallet-dev delete configmap revwallet-dashboard
  kubectl -n revwallet-dev delete configmap nginx-conf
  kubectl -n revwallet-dev delete configmap nginx-html
  kubectl -n revwallet-dev delete configmap nginx-htpasswd
  exit 0
fi

helm repo add grafana https://grafana.github.io/helm-charts
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

helm repo update

kubectl get pods -n revwallet-dev

echo "############## Deploying RevWallet DB ##############"
kubectl apply -f k8s/revwallet-db
echo -ne "####################################################\n\n"

echo "############## Deploying Alloy ##############"
kubectl -n revwallet-dev create configmap alloy-config --from-file=config/alloy/config.alloy
helm -n revwallet-dev upgrade --install --values k8s/alloy/values.yaml alloy grafana/alloy
echo -ne "##############################################\n\n"

echo "############## Deploying Loki ##############"
helm -n revwallet-dev upgrade --install --values k8s/loki/values.yaml loki grafana/loki-stack
echo -ne "############################################\n\n"

echo "############## Deploying Prometheus ##############"
helm -n revwallet-dev upgrade --install --values k8s/prometheus/values.yaml prometheus prometheus-community/prometheus
echo -ne "##################################################\n\n"

echo "############## Deploying Grafana ##############"
kubectl -n revwallet-dev create configmap revwallet-dashboard --from-file=config/grafana/dashboard.json
helm -n revwallet-dev upgrade --install --values k8s/grafana/values.yaml grafana grafana/grafana
echo -ne "###############################################\n\n"

echo "############## Deploying RevWallet API ##############"
helm -n revwallet-dev upgrade --install --values k8s/revwallet-api-chart/values.yaml revwallet-api k8s/revwallet-api-chart
echo -ne "#####################################################\n\n"

echo "############## Deploying Nginx ##############"
kubectl -n revwallet-dev create configmap nginx-html --from-file=config/nginx/revwallet.html --from-file=config/nginx/404.html 
kubectl -n revwallet-dev create configmap nginx-conf --from-file=config/nginx/nginx.conf
kubectl -n revwallet-dev create configmap nginx-htpasswd --from-file=config/nginx/.htpasswd
helm -n revwallet-dev upgrade --install --values k8s/nginx/values.yaml nginx bitnami/nginx
echo -ne "##############################################\n\n"

kubectl get pods -n revwallet-dev


