#!/bin/bash

curl -L -X GET http://revwallet.com/wallet/

for ((i=1; i<=100; i++))
do
  curl -L -X POST http://revwallet.com/wallet/ \
    -H "Content-Type: application/json" \
    -d '{"owner": "test", "initial_balance": "999.00", "currency": "EUR"}'

  curl -L -X GET "http://revwallet.com/wallet/balance/$i"
  curl -L -X GET http://revwallet.com/wallet/
done
