#!/bin/bash

# Port-forward to the nginx pod to be able to access the RevWallet API locally

NAMESPACE="revwallet-dev"
PID_FILE="port-forward.pid"

function stop_port_forward () {
  echo "Deleting port-forward..."

  if [ -f $PID_FILE ]; then
    echo "Stopping port-forward..."
    kill "$(cat $PID_FILE)"
    rm "$PID_FILE"
    echo "Port-forward stopped."
  else
    echo "No port-forward process found."
  fi
}

function start_port_forward () {
  delete_port_forward  # Make sure there is no port-forward running

  echo "Waiting for the API pod to be in the running state..."
  kubectl -n $NAMESPACE wait --for=condition=Ready pod -l app=revwallet-api

  echo "Waiting for the nginx pod to be in the running state..."
  kubectl -n $NAMESPACE wait --for=condition=Ready pod -l app=nginx

  echo "Find the pod name with the label app=nginx..."
  pod_name=$(kubectl -n $NAMESPACE get pods -l app=nginx -o jsonpath='{.items[0].metadata.name}')

  echo "Run the port-forward command in the background"
  kubectl -n $NAMESPACE port-forward "$pod_name" 8080:8080 > port-forward.log 2>&1 &

  echo $! > $PID_FILE
  echo "Port-forward started with PID $(cat $PID_FILE)."

  kubectl -n $NAMESPACE get pods
}

if [ "$1" == "--stop" ]; then
    stop_port_forward
else
    start_port_forward
fi