name: Chart CI

on:
  pull_request:
    paths:
      - 'charts/**'
      - '.github/workflows/chart-ci.yaml'

jobs:
  chart-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Create K8s clusters
        run: make local-create 
        
      - name: Deploy Services
        run: make local-db local-prometheus local-alloy local-loki local-grafana

      - name: Deploy RevWallet API (chart from current branch)
        run: |
          helm -n revwallet-dev install --values helm/revwallet-api/values.yaml revwallet-api charts/revwallet-api
          
      - name: Deploy Nginx
        run: make local-nginx

      - name: Run tests for K8s
        run: make tests
