name: Chart CI

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  tests-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Deploy API in K8s (CD)
        run: make create deploy

      - name: Run tests for K8s
        run: make tests
