name: ci

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv sync --dev

      - name: Start containers
        run: docker compose up -d --build

      - name: Run tests
        run: pipenv run pytest
      
      - name: Stop containers and remove volumes
        if: always()
        run: docker compose down -v