name: ci

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'img/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Start containers
        run: make compose-up

      - name: Run tests
        run: make tests
      
      - name: Stop containers and remove volumes
        if: always()
        run: make compose-down
