name: Tests

on:
  workflow_call:
    inputs:
      is_ci:
        type: boolean
        required: false
        default: false
      image_tag:
        type: string
        required: false
        default: 'latest'

jobs:
  tests-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Start containers
        run: make compose-up

      - name: Run tests for Docker Compose
        run: make tests
      
  tests-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Use the image built in CI for testing
        if: inputs.is_ci == true
        run: |
          TAG=$${{ inputs.image_tag }}

          echo "Updating helm chart with new image tag $TAG"
          sed -i "s|tag:.*|tag: ${TAG}|" helm/revwallet-api/values.yaml

      - name: Deploy API in K8s
        run: make create deploy

      - name: Run tests for K8s
        run: make tests
      