name: Tests

on:
  workflow_call:

jobs:
  tests-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Start containers
        run: make compose-up

      - name: Run tests for Docker Compose
        run: make tests
      
  tests-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Use the image built in CI for testing
        run: |
          GITHUB_SHA=$(git rev-parse HEAD)

          echo "Updating helm chart with new image tag $GITHUB_SHA"
          sed -i "s|tag:.*|tag: ${GITHUB_SHA}|" helm/revwallet-api/values.yaml

      - name: Deploy API in K8s
        run: make create deploy

      - name: Run tests for K8s
        run: make tests
      